### ISSUE TITLE
supervisor

### ISSUE THREAD

**Issue by benjiqq** [replikativ/kabel#5]
```
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
Exception in thread "main" java.lang.RuntimeException: No such var: async/poll!, compiling:(superv/async.cljc:757:5)
...
Caused by: java.lang.RuntimeException: No such var: async/poll!
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7188)
	at clojure.lang.Compiler.resolve(Compiler.java:7158)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7119)
	at clojure.lang.Compiler.analyze(Compiler.java:6680)
	... 309 more
```

**Comment by benjiqq** [comment]
fixed by removing other async dependency
